<?php
// module/Rubrique/view/sousrubrique/sousrubrique/index.phtml:
$title = 'Domaine des vieux celliers - Back office';
//$this->headTitle($title);
?>
    <style>
        span {
            width: 150px;
        }

        div label {
            width: 150px;
        }

        div#divlogincaptcha pre {
            width: 240px;
            text-align: center;
            font-size: 7px;
            line-height: 7px;
            padding: 0px 9.5px 0px 9.5px;
        }

        div#divlogincaptcha legend {
            width: 240px;
            font-size: 14px;
            font-weight: normal;
            line-height: 20px;
            border: none;
            display: block;
            padding: 0;
            margin-bottom: 0px;
        }

        div input {
            width: 250px;
            height: 40px;
        }

        #submitbutton {
            width: 265px;
            height: 40px;
        }

        #sweethoney {
            display: none;
        }

        #loginContainer {
            margin: 0 auto;
            width: 250px;

        }

        #loginTitle {
            text-align: center;
        }

        #divpwdhidden {
            display: none;

        }


    </style>
    <script type="text/javascript">
        $(document).ready(function () {

            $('#passwordIdTag').prop('readonly', true);
            $('#passwordIdTag').on('focus', function () {
                $('#passwordIdTag').removeAttr('readonly');
            });
            setTimeout(function(){
                $('#passwordIdTag').trigger('focus');
            }, 200);
            setTimeout(function(){
                $('#usernameIdTag').trigger('focus');
            }, 400);


            $('#submitbutton').on('click', function () {
                //hash password before submiting
                var shaObj = new jsSHA("SHA-512", "TEXT");
                shaObj.update($('#passwordIdTag').val());
                $('#passwordIdTag').val(shaObj.getHash("HEX"));
                document.login.submit();

            });
        });


    </script>
    <h2 id="loginTitle"><?php echo $title; ?></h2>


<?php
echo '<div id="loginContainer">';
$loginaccess = new \Zend\Session\Container('error');
if ($loginaccess->error) {
    echo '<div style="color:red;">' . $loginaccess->error . '</div>';
    $loginaccess->getManager()->getStorage()->clear('error');
}


$form = $this->form;
$form->setAttribute('action', $this->url('Login', array('action' => 'auth')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('prevent'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo '<div id="divlogincaptcha">';
echo $this->formRow($form->get('logincaptcha'));
echo '</div>';
echo $this->formRow($form->get('sweethoney'));
echo $this->formButton($form->get('submitbutton'));
echo $this->form()->closeTag();
echo '</div>';
    
    
    