<?php
// module/Album/view/rubrique/rubrique/delete.phtml:
$title = $this->translate('Supprimer un utilisateur');
$this->headTitle($title);
?>
<?php //print_r($rubrique); ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate('&Ecirc;tes-vous s&ucirc;r de vouloir supprimer cette utilisateur').' \''.$this->escapeHtml($login->getEmail()); ?>'?
</p>
<?php
	$url = $this->url('privatespacelogin', array(
		'action' => 'delete',
		'id' => $this->id,
	));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo (int) $login->getId(); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Oui'); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Non'); ?>" />
	</div>
</form>