<?php
// module/rubrique/view/rubrique/rubrique/add.phtml:
$title = $this->translate('Ajouter un nouvel utilisateur');
$this->headTitle($title);
?>

<style>
    div label{
        width:150px;
    }

    div input[type="submit"], #submitbutton{
        width:80px;
        height:40px;
    }
    form ul{
        display: none;
        
    }


</style>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if (is_array($error)) {
    foreach ($error as $value) {
        //var_dump($error);
        
        foreach($value as $message){
            //print_r($error);
            echo '<div style="color:red;">' . $message . '</div>';
        }
    }
}
?>
    
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('loginmgmt', array('action' => 'add')));
	
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('name'));
        echo '<br>'.$this->translate('Le nouveau mot de passe doit avoir 5 caractères');
        echo $this->formRow($form->get('pwd'));
        echo '<br>'.'<br>'.$this->formSelect($form->get('roleList'));
        echo '<br>'.'<br>'.$this->formButton($form->get('submitbutton'));
	
?>

<script type="text/javascript">
    $(document).ready(function () {
        $('#submitbutton').on('click', function(){
           //hash password before submiting 
           var shaObj = new jsSHA("SHA-512", "TEXT");
           
           var checkPwd = checkBeforeSubmitting($('#pwdIdTag').val());
           
            if(checkPwd.hash){
                shaObj.update(checkPwd.pwd);
                $('#pwdIdTag').val(shaObj.getHash("HEX"));
                //console.log(shaObj.getHash("HEX"));
                document.loginmgmt.submit();
            }
            else{
                document.loginmgmt.submit();
            }
        });
    });
    
    function checkBeforeSubmitting(pwd){
        var whatToDo = {};
        whatToDo.hash = true;
        //trim string with a regex
        pwd = pwd.replace(/^\s+|\s+$/gm,'');
        
        whatToDo.pwd = pwd;
        
        if(pwd.length < 5){
            whatToDo.hash = false;
        }
        
                
        return whatToDo;
        
    }
   
    
</script>
