<?php
// module/Rubrique/view/sousrubrique/sousrubrique/index.phtml:
$title = $this->translate('Changer votre mot de passe');
//$this->headTitle($title);
?>
<style>
    span{
        width:150px;
    }
    div label{
        width:150px;
    }
    
    div#divlogincaptcha pre{
        width:200px;
        text-align: center;
        font-size: 7px;
        line-height: 7px;
        padding:0px 9.5px 0px 9.5px;
    }
    
    div#divlogincaptcha legend{
        width:200px;
        font-size: 14px;
        font-weight: normal;
        line-height: 20px;
        border: none;
        display: block;
        padding: 0;
        margin-bottom: 0px;
    }
    
    div input[type="submit"], #submitbutton{
        width:80px;
        height:40px;
    }

    #sweethoney{
        display: none;
    }
    #loginContainer{
        //position: relative;
        margin: 0 auto;
        width:200px;

    }
    #loginTitle{
        text-align: center;
    }
    
    #divpwdhidden{
        display: none;
        
    }


</style>

<h2 id="loginTitle"><?php echo $title; ?></h2>
<script type="text/javascript">
    $(document).ready(function () {
        $('#submitbutton').on('click', function () {

            var pwd = $('#pwdIdTag').val();
            var confirmPwd = $('#pwdconfirmIdTag').val();

            if (pwd != confirmPwd) {
                bootbox.alert("<?php echo $this->translate("Les mots de passe ne sont pas identiques"); ?>");
                return false;
            }
            if (pwd.length < 5) {
                bootbox.alert("<?php echo $this->translate("Le mot de passe doit contenir 5 caractères minimum"); ?>");
                return false;
            }
            else {
                //hash password before submiting 
                var shaObj = new jsSHA("SHA-512", "TEXT");

                var checkPwd = checkBeforeSubmitting(pwd);
                var checkPwdConfirm = checkBeforeSubmitting(confirmPwd);
                if (checkPwd.hash && checkPwdConfirm.hash) {
                    shaObj.update(checkPwd.pwd);
                    $('#pwdIdTag').val(shaObj.getHash("HEX"));
                    shaObj.update(checkPwdConfirm.pwd);
                    $('#pwdconfirmIdTag').val(shaObj.getHash("HEX"));
                    //console.log(shaObj.getHash("HEX"));
                    document.privatespacelogin.submit();
                }
                else {
                    document.privatespacelogin.submit();
                }
            }

        });
    });

    function checkBeforeSubmitting(pwd) {
        var whatToDo = {};
        whatToDo.hash = true;
        //trim string with a regex
        pwd = pwd.replace(/^\s+|\s+$/gm, '');

        whatToDo.pwd = pwd;

        if (pwd.length < 5) {
            whatToDo.hash = false;
        }


        return whatToDo;

    }


</script>


<?php
if (is_array($error)) {
    foreach ($error as $value) {
        //var_dump($error);

        foreach ($value as $message) {
            //print_r($error);
            echo '<div style="color:red;">' . $message . '</div>';
        }
    }
}


    $form = $this->form;
    $form->setAttribute('action', $this->url('siteprivate', array('action' => 'changepassword')));
    $form->prepare();

    echo $this->form()->openTag($form);
    //TODO echo email address
    echo $this->formHidden($form->get('token'));
    echo $this->formHidden($form->get('prevent'));
    echo $this->formRow($form->get('pwd'));
    echo $this->formRow($form->get('pwdconfirm'));
    echo '<div id="divlogincaptcha">';
    echo $this->formRow($form->get('logincaptcha'));
    echo '</div>';
    echo $this->formRow($form->get('sweethoney'));
    echo $this->formButton($form->get('submitbutton'));
    echo $this->form()->closeTag();
    echo '</div>';

    