<?php
// module/Rubrique/view/sousrubrique/sousrubrique/index.phtml:
$title = $this->translate('Retrouver mon mot de pase');
//$this->headTitle($title);
?>
<style>
    span{
        width:150px;
    }
    div label{
        width:150px;
    }

    div#divlogincaptcha pre{
        width:200px;
        text-align: center;
        font-size: 7px;
        line-height: 7px;
        padding:0px 9.5px 0px 9.5px;
    }

    div#divlogincaptcha legend{
        width:200px;
        font-size: 14px;
        font-weight: normal;
        line-height: 20px;
        border: none;
        display: block;
        padding: 0;
        margin-bottom: 0px;
    }

    div input[type="submit"], #submitbutton{
        width:80px;
        height:40px;
    }

    #sweethoney{
        display: none;
    }
    #loginContainer{
        margin: 0 auto;
        width:200px;

    }
    #loginTitle{
        text-align: center;
    }

    #divpwdhidden{
        display: none;

    }


</style>

<h2 id="loginTitle"><?php echo $title; ?></h2>


<?php
if (is_array($error)) {
    foreach ($error as $value) {
        //var_dump($error);

        foreach ($value as $message) {
            //print_r($error);
            echo '<div style="color:red;">' . $message . '</div>';
        }
    }
}


$form = $this->form;
$form->setAttribute('action', $this->url('siteprivate', array('action' => 'forgottenpassword')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('prevent'));
echo '<div>' . $this->translate('Veuillez saisir votre addresse email') . '</div>';
echo $this->formRow($form->get('email'));
//echo '<div>' . $this->translate('Votre espace') . '</div>' . $this->formSelect($form->get('spacesList'));
echo '<div id="divlogincaptcha">';
echo $this->formRow($form->get('logincaptcha'));
echo '</div>';
echo $this->formRow($form->get('sweethoney'));
echo $this->formButton($form->get('submitbutton'));
echo $this->form()->closeTag();
echo '</div>';



