<?php
// module/Album/view/sousrubrique/sousrubrique/delete.phtml:
$title = $this->translate('Supprimer un fichier de la bibliothèque');
$this->headTitle($title);
?>
<?php //print_r($sousrubrique); ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate('&Ecirc;tes-vous s&ucirc;r de vouloir supprimer ce fichier'); ?>&nbsp;'<?php echo $this->escapeHtml($fichiers->getLibelle()); ?>'?
</p>
<?php
	$url = $this->url('Fichiers', array(
		'action' => 'delete',
		'id' => $this->id,
	));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo (int)$fichiers->getId(); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Oui') ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Non') ?>" />
	</div>
</form>