<?php
$title = $this->translate('Modifier les données associées au fichier');
$this->headTitle($title);
?>
<style>
div input[type="submit"]{
	width:80px;
	height:40px;
}

</style>


<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('Fichiers', array('action' => 'edit')));
	if($error!="no error"){
		echo '<div style="color:red;">'.$error.'</div>';
	}
	
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo '<div>'.$this->translate('Courte description').'</div>';
	echo $this->formRow($form->get('libelle'));
        echo '<div>'.$this->translate('Meta data').'</div>';
	echo $this->formRow($form->get('metadata'));
	echo '<div>&nbsp;</div>';
	echo '<div>'.$this->formSubmit($form->get('submit')).'</div>';
	
	echo $this->form()->closeTag();