<?php
// module/Rubrique/view/sousrubrique/sousrubrique/index.phtml:
$title = $this->translate('Mes Fichiers');
$this->headTitle($title);
?>
<style type="text/css">
    .imgView{
        cursor: pointer; 
    }
    
    img.imgpreview{
       display:block;
       margin: auto; 
    }
    
</style>
<script type="text/javascript">

    $(document).ready(function () {
        $("#tableSort").dataTable({
            language: {
                processing: "<?php echo $this->translate('Traitement en cours...'); ?>",
                search: "<?php echo $this->translate('Rechercher'); ?>&nbsp; ",
                lengthMenu: "<?php echo $this->translate('Afficher') . '_MENU_ ' . $this->translate('&eacute;l&eacute;ments'); ?>",
                info: "<?php echo $this->translate('Affichage de l\'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments') ?>",
                infoEmpty: "<?php echo $this->translate('Affichage de l\'&eacute;lement') . ' 0 &agrave; 0 ' . $this->translate('sur') . ' 0 ' . $this->translate('&eacute;l&eacute;ments') ?>",
                infoFiltered: "(<?php echo $this->translate('filtr&eacute; de ') . '_MAX_ ' . $this->translate('&eacute;l&eacute;ments au total'); ?>)",
                infoPostFix: "",
                loadingRecords: "<?php echo $this->translate('Chargement en cours'); ?>...",
                zeroRecords: "<?php echo $this->translate('Aucun &eacute;l&eacute;ment &agrave; afficher'); ?>",
                emptyTable: "<?php echo $this->translate('Aucune donnée disponible dans le tableau'); ?>",
                paginate: {
                    first: "<?php echo $this->translate('Premier'); ?>",
                    previous: "<?php echo $this->translate('Pr&eacute;c&eacute;dent') ?>",
                    next: "<?php echo $this->translate('Suivant') ?>",
                    last: "<?php echo $this->translate('Dernier') ?>"
                },
                aria: {
                    sortAscending: ": <?php echo $this->translate('activer pour trier la colonne par ordre croissant'); ?>",
                    sortDescending: ": <?php echo $this->translate('activer pour trier la colonne par ordre décroissant'); ?>"
                }
            },
            "aoColumnDefs": [
                {'bSortable': false, 'aTargets': [0, 4]}
            ]

        });
        /*
        $('#tableSort').on( 'search.dt', function () {
            $("img.imgView").off("click");
            $("img.imgView").on("click", function () {
                var linkToImg = $(this).attr("data-img");
                bootbox.alert("<img class='imgpreview' src='"+linkToImg+"' >");
            });
        });
        
        $('#tableSort').on( 'page.dt', function () {
            $("img.imgView").off("click");
            $("img.imgView").on("click", function () {
                var linkToImg = $(this).attr("data-img");
                bootbox.alert("<img class='imgpreview' src='"+linkToImg+"' >");
            });
        });
        */
        $('#tableSort').on( 'draw.dt', function () {
            $("img.imgView").off("click");
            $("img.imgView").on("click", function () {
                var linkToImg = $(this).attr("data-img");
                var extension = $(this).attr("data-filetype");
                if(extension == 'jpg' || extension == 'jpeg'
                    || extension == 'png' || extension == 'bmp'
                    || extension == 'gif' || extension == 'svg'){       
                    bootbox.alert("<img class='imgpreview' src='"+linkToImg+"' >");
                }
            });
        });   
           

        $("img.imgView").on("click", function () {
            var linkToImg = $(this).attr("data-img");
            var extension = $(this).attr("data-filetype");
            if(extension == 'jpg' || extension == 'jpeg'
               || extension == 'png' || extension == 'bmp'
               || extension == 'gif' || extension == 'svg'){       
                bootbox.alert("<img class='imgpreview' src='"+linkToImg+"' >");
            }
        });

    });

</script>


<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>&nbsp;</div>
<p><a class="btn btn-info" href="<?php
echo $this->url('Fichiers', array(
    'action' => 'add'));
?>"><?php echo $this->translate('Ajouter un fichier'); ?></a></p>
<div>&nbsp;</div>
<hr>
<table class="tablesorter table table-bordered table-striped hasFilters" id="tableSort" role="grid">
    <thead>
        <tr>
            <th style="width:10%; text-align:center; line-height:20px; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Aperçu'); ?></th>
            <th style="width:20%; text-align:center; line-height:20px; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Nom du fichier');?></th>
            <th style="width:20%; text-align:center; line-height:20px; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Description');?></th>
            <th style="width:20%; text-align:center; line-height:20px; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Meta Donn&eacute;es');?></th>
            <th style="width:20%; text-align:center; line-height:20px;" class="thheader" align="center"><?php echo $this->translate('Action'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php 
            
        foreach ($fichiers as $fichier) : 
        ?>

            <tr>
                <td style="width:10%; text-align:center; line-height:40px;"><img class="imgView" data-filetype="<?php echo $fichier->getType(); ?>" data-img="<?php 
                echo $this->basePath() . '/' . $fichier->getChemin() . $fichier->getNom() ?>" src="<?php
                echo $this->basePath() . '/' . $fichier->getThumbnailpath().'/'.$fichier->getThumbnail(); 
                
                
            ?>" width=40 height=40 /></td>

                <td style="width:20%; text-align:center; line-height:40px;"><?php echo $this->escapeHtml($fichier->getNom()); ?></td>
                <td style="width:20%; text-align:center; line-height:40px;"><?php echo $this->escapeHtml($fichier->getLibelle()); ?></td>
                <td style="width:20%; text-align:center; line-height:40px;"><?php echo $this->escapeHtml($fichier->getMetaData()); ?></td>
                <td style="width:20%; text-align:center; line-height:40px;">
                    <a href="<?php echo $this->url('Fichiers', array('action' => 'edit', 'id' => $fichier->getId()));
                                                                             ?>"><?php echo $this->translate('Modifier'); ?></a> /
                    <a href="<?php echo $this->url('Fichiers', array('action' => 'delete', 'id' => $fichier->getId()));
                                                                             ?>"><?php echo $this->translate('Supprimer'); ?></a>
                </td>
            </tr>
                   <?php endforeach; ?>
    </tbody>
</table>
