<?php
// module/rubrique/view/rubrique/rubrique/add.phtml:
$title = $this->translate('Modifier un Message');
$this->headTitle($title);
?>

<style>
    div label{
        width:150px;
    }

    div input[type="submit"], #submitbutton{
        width:80px;
        height:40px;
    }

    #contentText{
        width:700px;
        height:350px;
    }
    
    form ul{
        display: none;
        
    }

    input[name=timestamp]{
        display: block;
    }
    
</style>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/tinymce/tinymce.min.js'; ?>"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        language: 'fr_FR',
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste",
            "importcss"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright"
        });

        
        
        
   
    
    
    function soumettreajout(){
        
        if (validajout()){
            document.messageform.submit();
        }
    }


    function validajout(){
        
        
        
        //TODO Vérifier le format de la date
        /*
        //var position = document.messageform.position.value;
        // var isPosition = isNaN($.trim(position));
        //console.log(isNaN($.trim(position)));
        if(isPosition){
        //    console.log(isNan($.trim(position)));
           bootbox.alert('La position doit être vide ou être un nombre');
           return false;
        }
        */

        return true;
    }
    
    $(document).ready(function () {
        $('#submitbutton').on('click',function () {
            //alert('submit');
            soumettreajout();
        });

        $('.form_datetime').datetimepicker({
            //language:  'fr',
            //AAAA-MM-JJ HH:MM:SS
            format:"yyyy-mm-dd hh:ii:ss",
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            showMeridian: 1
        });
    });
    
</script>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('Message', array('action' => 'edit')));

$form->prepare();
if (is_array($error)) {
    foreach ($error as $value) {
        //var_dump($error);
        
        foreach($value as $message){
            //print_r($error);
            echo '<div style="color:red;">' . $message . '</div>';
        }
    }
}

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '<div>' . $this->formRow($form->get('row1')) . '</div>';
echo '<div>' . $this->formRow($form->get('row2')) . '</div>';
echo '<div>' . $this->formRow($form->get('row3')) . '</div>';
echo '<div>' . $this->formRow($form->get('row4')) . '</div>';
echo '<div>' . $this->formRow($form->get('type')) . '</div>';

echo '<div class="control-group">';
echo '<div class="controls input-append date form_datetime" data-date="" data-link-field="dtp_input1">';
echo '<div>' . $this->formRow($form->get('timestamp')) . '</div>';
echo '<span class="add-on"><i class="icon-remove"></i></span>';
echo '<span class="add-on"><i class="icon-th"></i></span>';
echo '</div>';
echo '<input type="hidden" id="dtp_input1" value="" /><br/>';
echo '</div>';

//echo '<div>' . $this->formRow($form->get('position')) . '</div>';
echo '<div id="contentText"><div>'.$this->translate('Contenu du message').'</div>' . $this->formTextarea($form->get('msg')) . '</div>';
echo '<div>' . $this->formButton($form->get('submitbutton')) . '</div>';
echo $this->form()->closeTag();
echo '<div>&nbsp;</div>';


//echo "Zend engine version: " . zend_version();
//print_r($fichiers);
	