<?php
	$title = $this->translate('Mes messages');
	$this->headTitle($title);
?>
<script type="text/javascript">

    $(document).ready(function () {
        $("#tableSort").dataTable({
            language: {
                processing: "<?php echo $this->translate('Traitement en cours...'); ?>",
                search: "<?php echo $this->translate('Rechercher'); ?>&nbsp; ",
                lengthMenu: "<?php echo $this->translate('Afficher') . '_MENU_ ' . $this->translate('&eacute;l&eacute;ments'); ?>",
                info: "<?php echo $this->translate('Affichage de l\'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments') ?>",
                infoEmpty: "<?php echo $this->translate('Affichage de l\'&eacute;lement') . ' 0 &agrave; 0 ' . $this->translate('sur') . ' 0 ' . $this->translate('&eacute;l&eacute;ments') ?>",
                infoFiltered: "(<?php echo $this->translate('filtr&eacute; de ') . '_MAX_ ' . $this->translate('&eacute;l&eacute;ments au total'); ?>)",
                infoPostFix: "",
                loadingRecords: "<?php echo $this->translate('Chargement en cours'); ?>...",
                zeroRecords: "<?php echo $this->translate('Aucun &eacute;l&eacute;ment &agrave; afficher'); ?>",
                emptyTable: "<?php echo $this->translate('Aucune donnée disponible dans le tableau'); ?>",
                paginate: {
                    first: "<?php echo $this->translate('Premier'); ?>",
                    previous: "<?php echo $this->translate('Pr&eacute;c&eacute;dent') ?>",
                    next: "<?php echo $this->translate('Suivant') ?>",
                    last: "<?php echo $this->translate('Dernier') ?>"
                },
                aria: {
                    sortAscending: ": <?php echo $this->translate('activer pour trier la colonne par ordre croissant'); ?>",
                    sortDescending: ": <?php echo $this->translate('activer pour trier la colonne par ordre décroissant'); ?>"
                }
            },
            aoColumnDefs : [ {
            bSortable : false,
            aTargets : [5]
        } ]
        });        
    });

</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>&nbsp;</div>
<p><a class="btn btn-info" href="<?php echo $this->url('Message', array('action' => 'add')); ?>"><?php echo $this->translate('Ajouter un message'); ?></a></p>
<div>&nbsp;</div>
<hr>
<table class="tablesorter table table-bordered table-striped hasFilters" id="tableSort" role="grid">
    <thead>
        <tr>
            <th style="text-align:center; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Ligne 1') ?></th>
            <th style="text-align:center; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Ligne 2') ?></th>
            <th style="text-align:center; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Ligne 3') ?></th>
            <th style="text-align:center; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Type') ?></th>
            <th style="text-align:center; cursor:pointer;" class="thheader" align="center"><?php echo $this->translate('Date') ?></th>
            <th style="text-align:center;" class="thheader" align="center"><?php echo $this->translate('Actions') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($messages as $message) : ?>
        <tr>
            <td style="text-align:center;"><?php echo $this->escapeHtml($message->getRow1()); ?></td>
            <td style="text-align:center;"><?php echo $this->escapeHtml($message->getRow2()); ?></td>
            <td style="text-align:center;"><?php echo $this->escapeHtml($message->getRow3()); ?></td>
            <td style="text-align:center;"><?php echo $this->escapeHtml($message->getType()); ?></td>
            <td style="text-align:center;"><?php echo $this->escapeHtml($message->getDate()); ?></td>
            <td style="text-align:center;">
                <a href="<?php echo $this->url('Message', array('action' => 'edit', 'id' => $message->getId()));
                ?>"><?php echo $this->translate('Modifier') ?></a>&nbsp;&nbsp;/&nbsp;
                <a href="<?php echo $this->url('Message', array('action' => 'delete', 'id' => $message->getId()));
        ?>"><?php echo $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>