<?php
// module/Album/view/rubrique/rubrique/delete.phtml:
$title = $this->translate('Supprimer un espace privé');
$this->headTitle($title);
?>
<?php //print_r($rubrique); ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate('Etes-vous sûr de vouloir supprimer cette espace privé ?'); ?> '<?php echo $this->escapeHtml($privatespace->getName()); ?>'?
</p>
<?php
	$url = $this->url('privatespace', array(
		'action' => 'delete',
		'id' => $this->id,
	));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo (int) $privatespace->getId(); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Oui'); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Non'); ?>" />
	</div>
</form>