<?php
// module/Album/view/sousrubrique/sousrubrique/delete.phtml:
$title = $this->translate('Supprimer un contenu de type blog');
$this->headTitle($title);
?>
<?php //print_r($sousrubrique); ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate('Etes-vous sûr de vouloir supprimer le contenu').' \''.$this->escapeHtml($contenu->getTitre()).'\' ?'; ?>
</p>
<?php
	$url = $this->url('Blogcontent', array(
		'action' => 'delete',
		'id' => $this->id,
	));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo (int) $contenu->getId(); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Oui'); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Non'); ?>" />
	</div>
</form>